apiVersion: v1
kind: Namespace
metadata:
  name: newdemo
spec:
  finalizers:
    - kubernetes
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgdevops
  namespace: newdemo
spec:
  replicas: 4   
  selector:
    matchLabels:
      app: dgdevops
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: dgdevops
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: dgdevops
          image: deepakgole/dgdevops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128M
            limits:
              cpu: '256'
              memory: 11400G
---
apiVersion: v1
kind: Service
metadata:
  name: dgdevops-service
  namespace: newdemo
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      name: port80
      port: 8080
      protocol: TCP
  selector:
    app: dgdevops